name: Job Crawler

on:
  schedule:
    - cron: '0 2 * * *'  # Chạy mỗi ngày lúc 2h sáng UTC
  push:
    branches: [ main ]    # Chạy khi có push vào branch main
  workflow_dispatch:      # Cho phép chạy thủ công từ GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run job crawler script
        run: python linkedin_crawler.py
