name: Job Crawler

on:
  schedule:
    - cron: '0 0 * * *' # Chạy mỗi ngày lúc 2h sáng UTC
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run job crawler script
        run: python linkedin_crawler.py

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add job_log.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update job_log.json [skip ci]" && git push)