name: Job Crawler

on:
  schedule:
    - cron: '0 3 * * *'  # Chạy mỗi ngày lúc 3h sáng UTC
  push:
    branches: [ main ]    # Chạy khi có push vào branch main
  workflow_dispatch:      # Cho phép chạy thủ công từ GitHub UI

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: |
          playwright install --with-deps
          
      - name: Run crawler
        run: python main.py
