name: Test Cron

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút (UTC)
  workflow_dispatch:        # Cho phép chạy thủ công

jobs:
  log-time:
    runs-on: ubuntu-latest

    steps:
      - name: Show UTC time
        run: date -u

      - name: Say hello
        run: echo "👋 Hello! This is a test cron job running every 5 minutes."
